### ISSUE TITLE
can not find `words-en`

### ISSUE THREAD

**Issue by alsotang** [espadrine/passphrase#2]
I just `npm i passphrase`, and write a file to test its function.

``` js
var passphrase = require('passphrase');
var entropy = 90;
passphrase(entropy, function(_, phrase, actualEntropy) {
  console.log('My passphrase is:', phrase);
});

```

then I got 

```
fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory './words-en'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at Object.<anonymous> (/Users/alsotang/Desktop/node_modules/passphrase/main.js:8:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/alsotang/Desktop/js.js:1:80)
```

**Comment by espadrine** [comment]
Thanks! Fixed.

**Comment by alsotang** [comment]
ok, it’s fixed
